services:
  frontend:
    build: ./nuxtpj
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./nuxtpj:/usr/src/app
    command: sh -c 'npm install && npm run dev'
    ports:
      - "3000:3000"
    tty: true

  nginx:
    image: nginx:1.21.1
    ports:
      - "80:80"
    volumes:
      - ./laravelpj/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./laravelpj/src:/var/www/
    depends_on:
      - php

  php:
    build: ./laravelpj/docker/php
    user: "1000:1000"
    volumes:
      - ./laravelpj/src:/var/www/
    ports:
      - "8000:8000"

  mysql:
    image: mysql:8.0.36
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./laravelpj/docker/mysql/data:/var/lib/mysql
      - ./laravelpj/docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=laravel_user
      - PMA_PASSWORD=laravel_pass
    depends_on:
      - mysql
    ports:
      - 8080:80
